/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDo;

public class App {
    public static void main(String[] args) {
        handleMainMenu();
    }

    private static void handleMainMenu() {
        String input = "";
        do {
            input = Screens.mainScreenDisplay();

            switch (input) {
                case "1": // Open ToDo List
                    Screens.openToDoMenu();
                    break;
                case "2"://  Display ToDo List
                    Screens.displayToDoMenu();
                    break;
                case "3"://  Add a ToDo List
                    Screens.addToDoMenu();
                    break;
                case "4"://  Edit ToDo List
                    Screens.editToDoMenu();
                    break;
                case "5"://  Delete ToDo List
                    Screens.deleteToDoMenu();
                    break;
                case "6"://  Save ToDo List
                    Screens.saveToDoMenu();
                    break;
                case "7"://  Exit
                    System.out.println("Thank you for using the ToDO List, Goodbye!");
                    break;
                default:
                    System.out.println("Unexpected value: " + input);
            }
        } while (!input.equals("7"));
    }
}